### Register
POST https://{{ base_url }}/register
Content-Type: application/json

{
  "email": "tcbenkhard2@gmail.com",
  "name": "Timo Benkhard",
  "password": "12345678"
}

### Login
POST https://{{ base_url }}/oauth/authorize
Authorization: Basic dGNiZW5raGFyZEBnbWFpbC5jb206MTIzNDU2Nzg=

### Get protected resource
GET https://{{ base_url }}/oauth/secure
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzUwMzU3NDAsImV4cCI6MTczNTEyMjE0MCwic3ViIjoidGNiZW5raGFyZEBnbWFpbC5jb20ifQ.m-mopvZu9p8HlqU8rVLz9_aqiPc0Rz-zBrbqh-dlck8ZeJdwb2hZBxx-Cpk0fSliJLe2mpRTLQc0Wq8NNpfcwLIR5UrNZmFPpYYPOE9bzE3bVtNMD-qI0-k5g7wn8l_kcYoOjt3hCAxUF_-zbBCofQ9uyHwvSBCyNvZJcZOwPsdjHJlgX6cCX_7eY2VGOfruRNPLDOtwm0hdNH18MxTDX-dkxweWEtnpGJyrUdCA5SmLIKSWN2KCm-XR0I82-HdoWDPqDAwhILaYZyBZZsP6RyeYEYkID6Vt1AyyzbuBW-oUChjcKiybePqh2erFNVgJKW3QeyKB63YTRFx58DJ8hg
