### Register
POST https://{{ base_url }}/register
Content-Type: application/json

{
  "email": "tcbenkhard@gmail.com",
  "name": "Timo Benkhard",
  "password": "12345678"
}

### Login
POST https://{{ base_url }}/oauth/authorize
Authorization: 

