### Register
POST https://{{ base_url }}/register
Content-Type: application/json

{
  "email": "tcbenkhard@gmail.com",
  "name": "Timo Benkhard",
  "password": "12345678"
}

### Login
POST https://{{ base_url }}/oauth/authorize
Authorization: Basic dGNiZW5raGFyZEBnbWFpbC5jb206MTIzNDU2Nzg=

### Get protected resource
GET https://{{ base_url }}/oauth/secure
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzQ5OTU5MjgsImV4cCI6MTczNTA4MjMyOCwic3ViIjoidGNiZW5raGFyZEBnbWFpbC5jb20ifQ.DD2RKvGmiQPNkgdiO4rEncWwfkaxG_hVAeCdmgE_Z6J-59GJ06P90yom7Vo30SSLVW8sfFb0hKmwgJPnmD80Bo_JGS1QrjneZxkBdopljwY84C9IPdS8g80OwGgHqJHlr9gWOQI0V-cyp7m5hkWvpdiKQCTQmTTTnbvHaFhEOpEwR2Znk45zcItAwrp46SRu2fIU8nDTxCyczDVqTgLlDMUOpiYuE-ZPgfnm36ITnAlYHblmHKxcmOVH69aS5jGWWRzqffPQb3AGIUdW39cDAtdOUbDrQJEpY72lAJyD-fB2d3bELKJfk6pJMbJcep3luDcNxlp2UllK3wmRXd1FvQ
